[package]
name = "todo"
version = "0.1.0"
authors = ["ymgyt <yamaguchi7073xtt@gmail.com>"]
edition = "2018"
exclude = ["front"]

[dependencies]
hyper = "0.13.5"
tokio = { version = "0.2.21", features = ["full"] }
futures = "0.3"
futures-util = "0.3.5"
pretty_env_logger = "0.4.0"
url = "2.1.1"
