# 実行時にわたすこともできる
# cargo make --env ENV1=VALUE1 --env ENV2=VALUE2
[env]
REACT_APP_VERSION = "v0.0.2"
REACT_APP_TODO_API_URL = "https://api-todo.ymgyt.io"

# frontend
[tasks.deploy_front]
script = [
  "cd front",
  "env | grep REACT_APP_",
  "npm run build",
  "aws s3 sync --delete build/ s3://todo.ymgyt.io/"
]

[tasks.run_front]
script = ["cd front && yarn start"]

# backend
[tasks.docker_build]
command = "docker"
args = ["build", "--tag", "todo", "."]

[tasks.docker_tag]
script = [
    "docker tag todo ymgyt/todo:${CARGO_MAKE_CRATE_VERSION:? required}",
    "docker tag todo ymgyt/todo:latest",
    "docker image ls --filter 'reference=ymgyt/todo'"
]

[tasks.docker_push]
script = [
    "docker push ymgyt/todo:${CARGO_MAKE_CRATE_VERSION:? required}"
]

[tasks.docker_flow]
dependencies = [
    "docker_build",
    "docker_tag",
    "docker_push"
]

[tasks.run_server]
script = ["TODO_PORT=4001 cargo run"]

[tasks.echo]
env = {"REACT_APP_TODO_API_URL" = "localhost:4002"}
script = [
    "echo ${REACT_APP_TODO_API_URL}",
    "env | grep CARGO_ | grep VERSION"
]

[tasks.never]
condition_script = [
    "exit 1"
]
script = ["echo never executed"]


